package rece

//constants for rece-processing
const (
	RSort          = 2 + 1
	RMNkensaku     = 6
	RMNkensakuDen  = 7
	RMNirnameDen   = 2 + 3
	RDenMnKensaku  = 7
	RIRprf         = 2 + 3
	RIRpnttbl      = 2 + 4
	RIRircode      = 2 + 5
	RIRirname      = 2 + 7
	RIRseikyuYm    = 2 + 8
	RIRseikyuYmDen = 2 + 7
	RIRseikyuYmPha = 2 + 7
	RYKprf         = 2 + 3
	RYKpnttbl      = 2 + 4
	RYKykcode      = 2 + 5
	RYKykname      = 2 + 6
	RYKseikyuYm    = 2 + 7
	RREshubetu     = 2 + 3
	RREsinryoYm    = 2 + 4
	RREname        = 2 + 5
	RREgender      = 2 + 6
	RREbirth       = 2 + 7
	RREinnDate     = 2 + 9
	RREkarte       = 2 + 14
	RREprfPha      = 2 + 10
	RREpnttblPha   = 2 + 11
	RREircodePha   = 2 + 12
	RREirnamePha   = 2 + 13
	RREkensaku     = 2 + 19
	RREphaKensaku  = 2 + 38
	RREdpcKensaku  = 2 + 21
	RREdenKensaku  = 2 + 20
	RREdpcSokatsu  = 2 + 19
	RHOhknsha      = 2 + 2
	RHOinsKigo     = 2 + 3
	RHOinsBango    = 2 + 4
	RHOjitudate    = 2 + 5
	RHOten         = 2 + 6
	RHOmealCnt     = 2 + 8
	RHOmealGaku    = 2 + 9
	RHOmealCntDen  = 2 + 7
	RHOmealGakuDen = 2 + 8
	RROhknsha      = 2 + 2
	RROinsKigo     = 2 + 3
	RROinsBango    = 2 + 4
	RROjitudate    = 2 + 5
	RROten         = 2 + 6
	RROmealCnt     = 2 + 8
	RROmealGaku    = 2 + 9
	RKOftn         = 2 + 2
	RKOrcv         = 2 + 3
	RKOjitudate    = 2 + 5
	RKOten         = 2 + 6
	RKOmealCnt     = 2 + 11
	RKOmealGaku    = 2 + 12
	RKOmealCntDen  = 2 + 9
	RKOmealGakuDen = 2 + 10
	RBUdpccd       = 2 + 2
	RBUinnDate     = 2 + 3
	RBUoutDate     = 2 + 4
	RBUtenki       = 2 + 5
	RBUreason      = 2 + 6
	RSJdetail      = 2 + 3
	RSYsybcd       = 2 + 2
	RSYstart       = 2 + 3
	RSYtenki       = 2 + 4
	RSYdeco        = 2 + 5
	RSYnm          = 2 + 6
	RSYmain        = 2 + 7
	RHSstart       = 2 + 2
	RHStenki       = 2 + 3
	RHSsisiki      = 2 + 4
	RHSsybcd       = 2 + 5
	RHSdeco        = 2 + 6
	RHSnm          = 2 + 7
	RHSmain        = 2 + 10
	RSHno          = 2 + 2
	RSHzaikei      = 2 + 3
	RSHyohocd      = 2 + 4
	RSSactCd       = 2 + 4
	RCZprscYmd     = 2 + 3
	RCZsuryo       = 2 + 6
	RIYbetuCd      = 2 + 2
	RIYdrugCd      = 2 + 3
	RIYamount      = 2 + 4
	RIYmedDrugCd   = 2 + 4
	RIYmedAmount   = 2 + 5
	RIYmedTen      = 2 + 6
	RIYmedCount    = 2 + 7
	RIYmedDay1     = 2 + 14
	RIYmedDay1Den  = 2 + 9
	RSIbetuCd      = 2 + 2
	RSIfutan       = 2 + 3
	RSIactCd       = 2 + 4
	RSInum         = 2 + 5
	RSIten         = 2 + 6
	RSIcnt         = 2 + 7
	RSIday1        = 2 + 14
	RSKactCd       = 2 + 2
	RSKkbnCd       = 2 + 3
	RSBsybcd       = 2 + 2
	RSBaffix       = 2 + 3
	RSBnm          = 2 + 4
	RSBicd10       = 2 + 5
	RSBkbn         = 2 + 6
	RMOiKi         = 6
	RMOiBan        = 7
	RMObirth       = 8
	RMOnm          = 11
	RMOknm         = 12
	RCDdpcYmd      = 2 + 2
	RCDdpcBetu     = 2 + 3
	RCDdpcRececd   = 2 + 6
	RCDdpcAmount   = 2 + 7
	RCDdpcCount    = 2 + 10
)

//RArrCzTen - Array for Locations of "Ten" on CZ line.
var RArrCzTen = [...]int{11 + 2, 18 + 2, 21 + 2, 24 + 2, 27 + 2, 30 + 2, 33 + 2, 36 + 2, 39 + 2, 42 + 2, 45 + 2}
